<?php 
class eventclass_support  extends eventsBase
{ 
	function eventclass_support()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


//	onscreen events


	}
// Captchas functions	

//	handlers

		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values,&$keys,$inline,&$pageObject)
{

		global $conn;

$companyemail='kopiaman@yahoo.com';

$inqury=$values['inquiry'];
$sdate=$values['sdate'];
$staff=$values['staff'];
$stitle=$values['stitle'];
$topic=$values['topic'];

//send to config
$to2 =$companyemail;
$subject2 =" CAMPSYS Support- $stitle  ";
$headers2 = "From: CAMPSYS Support <noreply@mataaviation.com> \r\n";
$headers2 .= "Content-type: text/html" ."\r\n";

$message2 ="<html><body>";
$message2 .="<p> $stitle </p><br > ";
$message2 .="<p> $staff </p><br > ";
$message2 .="<p> $sdate </p><br > ";
$message2 .="<p> $inqury </p><br > ";
$message2 .="<p style='font-size:10px'> **Note: This is automatic notification generated by our system***</p> ";
$message2 .= "</body></html>";
	
$mailto=mail($to2, $subject2, $message2, $headers2);
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values,$where,&$oldvalues,&$keys,$inline,&$pageObject)
{

		global $conn;


$inqury=$values['inquiry'];
$answer=$values['answer'];
$sdate=$values['sdate'];
$staff=$values['staff'];
$stitle=$values['stitle'];
$topic=$values['topic'];
$sstatus=$values['sstatus'];

//send to config
$to2 ='raizul@mataaviation.com';
$subject2 =" CAMPSYS Support-  $sstatus- $stitle  ";
$headers2 = "From: CAMPSYS Support <noreply@mataaviation.com> \r\n";
$headers2 .= "Content-type: text/html" ."\r\n";
$message2 ="<html><body>";
$message2 .="<p> <b> Status: </b> $sstatus </p>";
$message2 .="<p> <b>Title: </b> $stitle </p>";
$message2 .="<p> <b>Requestor: </b> $staff </p> ";
$message2 .="<p> <b>Date: </b> $sdate </p> ";
$message2 .="<p> <b>Inquiry: </b><br> $inqury </p><br><br> ";
$message2 .="<p><b> Answer:</b><br> $answer </p> <br> ";
$message2 .="<p style='font-size:10px'> **Note: This is automatic notification generated by our system***</p> ";
$message2 .= "</body></html>";

if($sstatus!='Pending'){
$mailto=mail($to2, $subject2, $message2, $headers2);
}else{};


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
//	onscreen events

} 
?>
